comments/comments/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comments_app.urls'))
]

comments/comments_app/urls.py
from django.urls import path
from . import views

app_name = 'comments_app'

urlpatterns = [
    path('', views.view_comment, name='view_comments'),
    path('comment/', views.add_comment, name='add_comment'),
    path('reply/', views.add_reply, name='add_reply'),
    path('edit/', views.edit_comment, name='edit_comment')
]

comments/comments_app/models.py
from datetime import datetime
from django.db import models

class Comment(models.Model):
    username = models.CharField(max_length=10, null=False)
    email = models.EmailField(max_length=30, null=False)
    text = models.CharField(max_length=500)
    created = models.DateTimeField(default=datetime.now)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text[:20]}"

comments/comments_app/forms.py
from django.forms import ModelForm, CharField, TextInput, HiddenInput
from .models import Comment


class CommentForm(ModelForm):

    username = CharField(min_length=3, max_length=10, required=True, widget=TextInput())
    email = CharField(min_length=3, max_length=20, required=True, widget=TextInput())
    text = CharField(min_length=3, max_length=500, required=True, widget=TextInput())
    
    class Meta:
        model = Comment
        fields = ['username', 'email', 'text', 'parent']
        widgets = {
            'parent': HiddenInput()
        }

comments/comments_app/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from comments_app.forms import CommentForm
from comments_app.models import Comment
from math import ceil

PAGE_SIZE = 25

def view_comment(request):
    order_by = request.GET.get("order_by") if request.GET.get("order_by") else "created"
    order = request.GET.get("order") if request.GET.get("order") != None else "-"
    page = int(request.GET.get("page")) if request.GET.get("page") else 0
    n_pages = ceil(Comment.objects.filter(parent__isnull=True).__len__() / PAGE_SIZE) - 1
    comments = Comment.objects.filter(parent__isnull=True).order_by(order + order_by)[page*PAGE_SIZE:(page+1)*PAGE_SIZE]
    form = CommentForm()
    return render(request, 'comments_app/view_comments.html', {'comments': comments, 'form': form, "order_by": order_by,
                                                               "order": order, "page": page, "n_pages": n_pages})

def add_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid() and request.POST.get("captcha") == request.POST.get("captcha_answer") and request.POST.get("captcha"):
            comment = form.save()
    return redirect(to='comments_app:view_comments')

def add_reply(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid() and request.POST.get("captcha") == request.POST.get("captcha_answer") and request.POST.get("captcha"):
            comment = form.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                comment_html = render_to_string('comments_app/comment.html', {'comment': comment}, request=request)
                return JsonResponse({'comment_html': comment_html})
    return HttpResponseBadRequest

def edit_comment(request):
    if request.method == 'POST':
        form = request.POST
        if len(form.get("new_text")) <= 500 and request.POST.get("captcha") == request.POST.get("captcha_answer") and request.POST.get("captcha"):
            comment = Comment.objects.get(id=int(form.get("id")))
            comment.text = form.get("new_text")
            comment.save()
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'new_text': form.get('new_text')})
    return HttpResponseBadRequest()

comments/comments_app/templates/comments_app/comment.html
<div class="comment">
    <p><strong>{{ comment.username }}</strong> - {{ comment.created }}</p>
    <p id="comment-text-{{comment.id}}">{{ comment.text }}</p>
    <a href="#" onclick="showEditForm( '{{comment.id}}' );">Edit</a>
    <div id="edit-form-{{comment.id}}" class="edit-form" style="display:none;">
        <form method="post" onsubmit="event.preventDefault(); submitEditForm(this);">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{comment.id}}">
            <input type="text" name="new_text" value="{{comment.text}}">
            <div onload="generate( 'edit-{{ comment.id }}' )" id="captcha-edit-{{ comment.id }}" selectable="False"></div>
            <input type="text" name="captcha" value="Enter symbols above">
            <input id="captcha-answer-edit-{{ comment.id }}" type="hidden" name="captcha_answer">
            <button type="button" onclick="generate('edit-{{ comment.id }}')">Regenerate captcha</button>
            <button type="submit">Submit</button>
        </form>
    </div>
    <a href="#" onclick="showReplies( '{{comment.id}}' );">See replies</a>
    <div id="replies-{{ comment.id }}" class="replies" style="display:none;">
        <a href="#" onclick="showReplyForm('{{ comment.id }}');">Reply</a>
        <div id="reply-form-{{ comment.id }}" class="reply-form" style="display:none;">
            <form method="post" onsubmit="event.preventDefault(); submitReplyForm(this);">
                {% csrf_token %}
                {{ form.as_p }}
                <div onload="generate( '{{ comment.id }}' )" id="captcha-{{ comment.id }}" selectable="False"></div>
                <input type="text" name="captcha" value="Enter symbols above">
                <input id="captcha-answer-{{ comment.id }}" type="hidden" name="captcha_answer">
                <button type="button" onclick="generate('{{ comment.id }}')">Regenerate captcha</button>
                <input type="hidden" name="parent" value="{{ comment.id }}">
                <button type="submit">Submit</button>
            </form>
        </div>
        {% for reply in comment.replies.all %}
            <div class="reply">
                {% include "comments_app/comment.html" with comment=reply %}
            </div>
        {% endfor %}
    </div>
</div>

comments/comments_app/templates/comments_app/view_comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comments</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 20px;
        }
        .comment {
            background-color: white;
            padding: 10px;
            margin: 10px 0;
            border-radius: 5px;
        }
        .reply {
            margin-left: 20px;
        }
        form {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Comments</h1>
    <a href="#" onclick="showSorting();">Sort comments</a>
    <div id="sorting" class="sorting" style="display:none;">
        <form action="" method="get">
            <label>Sort comments by: </label>
            <select id="order_by" name="order_by">
                <option value="created">Date</option>
                <option value="username">Username</option>
                <option value="email">Email</option>
            </select>
            <label>Order: </label>
            <select id="order" name="order">
                <option value="">Ascending</option>
                <option value="-">Descending</option>
            </select>
            <input type="submit" value="OK">
        </form>
    </div>
    <div id="comments">
        {% for comment in comments %}
            {% include "comments_app/comment.html" with comment=comment %}
        {% endfor %}
    </div>
    <a href="#" onclick="showCommentForm();">Comment</a>
    <div id="comment-form" class="comment-form" style="display:none;">
    <h2>Add a Comment</h2>
        <form method="post" action="{% url 'comments_app:add_comment' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div onload="generate()" id="captcha-0" selectable="False"></div>
            <input type="text" name="captcha" value="Enter symbols above">
            <input id="captcha-answer-0" type="hidden" name="captcha_answer">
            <button type="button" onclick="generate()">Regenerate captcha</button>
            <button type="submit">Submit</button>
        </form>
    </div>

    {% if page > 0 %}
        <form action="" method="get">
            <input type="hidden" name="order_by" value="{{ order_by }}">
            <input type="hidden" name="order" value="{{ order }}">
            <input type="hidden" name="page" value="{{ page|add:-1 }}">
            <input type="submit" value="Previus page">
        </form>
    {% endif %}
    {% if page < n_pages %}
        <form action="" method="get">
            <input type="hidden" name="order_by" value="{{ order_by }}">
            <input type="hidden" name="order" value="{{ order }}">
            <input type="hidden" name="page" value="{{ page|add:1 }}">
            <input type="submit" value="Next page">
        </form>
    {% endif %}

    <script>
        function changeVisibility(block) {
            if (block.style.display === 'none') {
                block.style.display = 'block';
            } else {
                block.style.display = 'none';
            }
        }
        function showReplyForm(commentId) {
            const replyForm = document.getElementById('reply-form-' + commentId);
            changeVisibility(replyForm)
            generate(commentId)
        }
        function showCommentForm() {
            const commentForm = document.getElementById('comment-form');
            changeVisibility(commentForm)
            generate()
        }
        function showReplies(commentId) {
            const replies = document.getElementById('replies-' + commentId);
            changeVisibility(replies)
        }
        function showSorting() {
            const sorting = document.getElementById('sorting');
            changeVisibility(sorting)
        }
        function showEditForm(commentId) {
            const editForm = document.getElementById('edit-form-' + commentId);
            changeVisibility(editForm)
            generate('edit-' + commentId)
        }

        function generate(captchaId=0) {
            let uniquechar = "";

            const randomchar =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

            for (let i = 1; i < 5; i++) {
                uniquechar += randomchar.charAt(
                Math.random() * randomchar.length)
            }
            const captcha = document.getElementById('captcha-' + captchaId);
            captcha.innerHTML = uniquechar;
            const captcha_answer = document.getElementById('captcha-answer-' + captchaId);
            captcha_answer.value = uniquechar;
        }

        function submitEditForm(form){
            const comment = new FormData(form);
            var request = new XMLHttpRequest();
            request.open('POST', '{% url "comments_app:edit_comment" %}', true)
            request.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
            request.onload = function() {
                if (request.status === 200) {
                    var response = JSON.parse(request.responseText);
                    var text = document.getElementById('comment-text-' + form.id.value)
                    text.innerText = response.new_text
                    form.reset();
                    form.style.display = 'none';
                }
            };
            request.send(comment);
        }
        function submitReplyForm(form){
            const reply = new FormData(form);
            var request = new XMLHttpRequest();
            request.open('POST', '{% url "comments_app:add_reply" %}', true)
            request.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
            request.onload = function() {
                if (request.status === 200) {
                    var response = JSON.parse(request.responseText);
                    var newReply = document.createElement('div');
                    newReply.className = "reply"
                    newReply.innerHTML = response.comment_html;
                    form.closest('.replies').appendChild(newReply);
                    form.reset();
                    form.style.display = 'none';
                }
            };
            request.send(reply);
        }
    </script>
</body>
</html>